
package ODB;

import java.awt.Image;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.JTextField;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import java.text.SimpleDateFormat;

public class RegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentManagementSystem
     */
    public RegistrationForm() {
        initComponents();
        image();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblFullname = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        cmdRegister = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();
        lvlTitle = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        lblUser1 = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        lblUser2 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPass2 = new javax.swing.JLabel();
        jBirthDate = new com.toedter.calendar.JDateChooser();
        lblPass3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        SeePassword = new javax.swing.JToggleButton();
        txtAddress = new javax.swing.JTextField();
        lblPass4 = new javax.swing.JLabel();
        lvlTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 69, 107));
        jPanel2.setLayout(null);

        txtFirstName.setBackground(new java.awt.Color(248, 241, 241));
        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(25, 69, 107));
        jPanel2.add(txtFirstName);
        txtFirstName.setBounds(20, 170, 220, 44);

        txtLastName.setBackground(new java.awt.Color(248, 241, 241));
        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(25, 69, 107));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtLastName);
        txtLastName.setBounds(20, 240, 220, 44);

        txtUsername.setBackground(new java.awt.Color(248, 241, 241));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(25, 69, 107));
        jPanel2.add(txtUsername);
        txtUsername.setBounds(20, 100, 220, 44);

        lblFullname.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(248, 241, 241));
        lblFullname.setText("First Name");
        jPanel2.add(lblFullname);
        lblFullname.setBounds(20, 140, 110, 30);

        lblUser.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(248, 241, 241));
        lblUser.setText("Last Name");
        jPanel2.add(lblUser);
        lblUser.setBounds(20, 210, 110, 30);

        lblPass.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(248, 241, 241));
        lblPass.setText("Username");
        jPanel2.add(lblPass);
        lblPass.setBounds(20, 70, 70, 30);

        cmdRegister.setEnabled(false);
        cmdRegister.setBackground(new java.awt.Color(22, 199, 154));
        cmdRegister.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cmdRegister.setForeground(new java.awt.Color(25, 69, 107));
        cmdRegister.setText("Register");
        cmdRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdRegisterMouseClicked(evt);
            }
        });
        cmdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(cmdRegister);
        cmdRegister.setBounds(20, 470, 210, 44);

        cmdExit.setBackground(new java.awt.Color(22, 199, 154));
        cmdExit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        cmdExit.setForeground(new java.awt.Color(25, 69, 107));
        cmdExit.setText("Exit");
        cmdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdExitMouseClicked(evt);
            }
        });
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        jPanel2.add(cmdExit);
        cmdExit.setBounds(240, 470, 240, 44);

        lvlTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lvlTitle.setForeground(new java.awt.Color(248, 241, 241));
        lvlTitle.setText("Tahongan ni Geneva");
        jPanel2.add(lvlTitle);
        lvlTitle.setBounds(160, 10, 220, 20);

        txtMiddleName.setBackground(new java.awt.Color(248, 241, 241));
        txtMiddleName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMiddleName.setForeground(new java.awt.Color(25, 69, 107));
        txtMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiddleNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtMiddleName);
        txtMiddleName.setBounds(260, 170, 220, 44);

        lblUser1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUser1.setForeground(new java.awt.Color(248, 241, 241));
        lblUser1.setText("Middle Name");
        jPanel2.add(lblUser1);
        lblUser1.setBounds(260, 140, 110, 30);

        lblPass1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(248, 241, 241));
        lblPass1.setText("Password");
        jPanel2.add(lblPass1);
        lblPass1.setBounds(260, 70, 70, 30);

        lblUser2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblUser2.setForeground(new java.awt.Color(248, 241, 241));
        lblUser2.setText("Contact Number");
        jPanel2.add(lblUser2);
        lblUser2.setBounds(20, 280, 140, 30);

        txtContactNo.setBackground(new java.awt.Color(248, 241, 241));
        txtContactNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContactNo.setForeground(new java.awt.Color(25, 69, 107));
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        jPanel2.add(txtContactNo);
        txtContactNo.setBounds(20, 310, 220, 44);

        txtEmail.setBackground(new java.awt.Color(248, 241, 241));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(25, 69, 107));
        jPanel2.add(txtEmail);
        txtEmail.setBounds(260, 310, 220, 44);

        lblPass2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPass2.setForeground(new java.awt.Color(248, 241, 241));
        lblPass2.setText("Birthday ");
        jPanel2.add(lblPass2);
        lblPass2.setBounds(260, 210, 90, 30);

        jBirthDate.setBackground(new java.awt.Color(248, 241, 241));
        jBirthDate.setForeground(new java.awt.Color(25, 69, 107));
        jPanel2.add(jBirthDate);
        jBirthDate.setBounds(260, 240, 220, 44);

        lblPass3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPass3.setForeground(new java.awt.Color(248, 241, 241));
        lblPass3.setText("Email");
        jPanel2.add(lblPass3);
        lblPass3.setBounds(260, 280, 90, 30);

        jCheckBox1.setOpaque(false);
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(248, 241, 241));
        jCheckBox1.setText("I agree to the Company's Terms and Conditions");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(80, 440, 340, 24);

        txtPassword.setBackground(new java.awt.Color(248, 241, 241));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(25, 69, 107));
        jPanel2.add(txtPassword);
        txtPassword.setBounds(260, 100, 190, 44);

        SeePassword.setOpaque(false);
        SeePassword.setContentAreaFilled(false);
        SeePassword.setBorderPainted(false);
        SeePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SeePasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SeePasswordMouseReleased(evt);
            }
        });
        jPanel2.add(SeePassword);
        SeePassword.setBounds(450, 100, 40, 40);

        txtAddress.setBackground(new java.awt.Color(248, 241, 241));
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(25, 69, 107));
        jPanel2.add(txtAddress);
        txtAddress.setBounds(20, 380, 460, 44);

        lblPass4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPass4.setForeground(new java.awt.Color(248, 241, 241));
        lblPass4.setText("Address");
        jPanel2.add(lblPass4);
        lblPass4.setBounds(20, 350, 90, 30);

        lvlTitle1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        lvlTitle1.setForeground(new java.awt.Color(248, 241, 241));
        lvlTitle1.setText("Registration Form");
        jPanel2.add(lvlTitle1);
        lvlTitle1.setBounds(100, 30, 310, 50);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void cmdExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseClicked
            
        
                    
    }//GEN-LAST:event_cmdExitMouseClicked

    private void cmdRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdRegisterMouseClicked
    
    }//GEN-LAST:event_cmdRegisterMouseClicked

    private void txtMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiddleNameActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void cmdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegisterActionPerformed
    String sql = "INSERT INTO usertable (Username, Password, First_Name, Middle_Name, Last_Name, Birthday, Contact_Number, Email, Address) Values(?,?,?,?,?,?,?,?,?)";
    
    try {
        PreparedStatement preparedstatement = Database.myConnect("posdatabase").prepareStatement(sql);
        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String firstname = txtFirstName.getText();
        String middlename = txtMiddleName.getText();
        String lastname = txtLastName.getText();
        SimpleDateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy");
        String birthdate = dateformat.format(jBirthDate.getDate());
        String contactnum = txtContactNo.getText();
        String email = txtEmail.getText();
        String address = txtAddress.getText();
        
        
        preparedstatement.setString(1, username);
        preparedstatement.setString(2, password);
        preparedstatement.setString(3, firstname);
        preparedstatement.setString(4, middlename);
        preparedstatement.setString(5, lastname);
        preparedstatement.setString(6, birthdate);
        preparedstatement.setString(7,contactnum);
        preparedstatement.setString(8, email);
        preparedstatement.setString(9, address);
        
        preparedstatement.executeUpdate();
        
        JOptionPane.showMessageDialog(this,"Registration complete", "Prompt",JOptionPane.PLAIN_MESSAGE );
        preparedstatement.close();

    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    login LG = new login();
    LG.show();
    this.hide();
    }//GEN-LAST:event_cmdRegisterActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()){
        cmdRegister.setEnabled(true);
        }
        else{
        cmdRegister.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void SeePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeePasswordMousePressed
    txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_SeePasswordMousePressed

    private void SeePasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeePasswordMouseReleased
    txtPassword.setEchoChar('•');
    }//GEN-LAST:event_SeePasswordMouseReleased

    
    
    
    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
    int cmdExit = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit?", "EXIT", JOptionPane.YES_NO_OPTION);
        switch (cmdExit){
            case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(this,"Thank you for trying to register.");
                login logs = new login();
                logs.setVisible(rootPaneCheckingEnabled);
                this.dispose();
            case JOptionPane.NO_OPTION:
        }
    }//GEN-LAST:event_cmdExitActionPerformed

   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    
public void image(){
    ImageIcon icon = new ImageIcon(getClass().getResource("/view.png"));
    int offset = SeePassword.getInsets().left;
    SeePassword.setIcon(resizeIcon(icon, SeePassword.getWidth() - offset, SeePassword.getHeight() - offset));
}    

private static Icon resizeIcon(ImageIcon icon, int resizedWidth, int resizedHeight) {
    Image img = icon.getImage();  
    Image resizedImage = img.getScaledInstance(resizedWidth, resizedHeight,  java.awt.Image.SCALE_SMOOTH);  
    return new ImageIcon(resizedImage);
}    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton SeePassword;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdRegister;
    private com.toedter.calendar.JDateChooser jBirthDate;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPass3;
    private javax.swing.JLabel lblPass4;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblUser2;
    private javax.swing.JLabel lvlTitle;
    private javax.swing.JLabel lvlTitle1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
